[workspace]
members = [
    "lib",
    "program",
    "script",
    "visual",
    "visual/egui_graphs",
    "contracts/ping",
]
resolver = "2"


[workspace.dependencies]
alloy-sol-types = "1.0"
petgraph = "0.8.2"
graphalgs = "0.2"
rand = "0.8"                                                      # graphalgs
freenet-stdlib = { version = "0.1.11" }
freenet-ping-types = { path = "types", default-features = false }
chrono = { version = "0.4", default-features = false }

# rand crate sucks. so much renaming from 0.8 to 0.9
