[package]
name = "visual"
version = "0.1.0"
edition = "2024"


[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_graphs = { path = "./egui_graphs", features = ["events"] }
petgraph = { workspace = true }
smt = { version = "0.12.0", path = "../lib" }
graphalgs = { workspace = true }
rand = { workspace = true }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
fdg = { path = "./fdg", version = "1.0.0", features = ["serde"]}
